### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by XVilka** [seemoo-lab/internalblue#10]
Python 2 is being deprecated [in a month](https://pythonclock.org), some distributions, e.g. Fedora, started to remove python2-related packages from the default installations. Would be awesome to migrate this tool too.

**Comment by fmagin** [comment]
This is currently being worked on by @unixb0y and me.

We will not be in time for the the deprecation, but expect it to be done around February/March 2020.

**Comment by jiska2342** [comment]
Finally merged :D
