### ISSUE TITLE
The question about how to get LMP packets

### ISSUE THREAD

**Issue by KaiLai-CH** [seemoo-lab/internalblue#36]
Hi there,  
I try to using the CYW20735 evaluation board connect to android system, 
but only watch the hci_h4 & L2CAP data on wireshark, and can't watch the LMP data.
So I can't watch LMP is because I didn't install the patch on the evaluation board, or other problem ?

Thanks in advance !

**Comment by jiska2342** [comment]
I further detailed kernel modification here:
https://github.com/seemoo-lab/internalblue/blob/master/linux/bias_linux-4.14.111.diff
