### ISSUE TITLE
Can Internalblue work with upper layer protocol?

### ISSUE THREAD

**Issue by LHKST** [seemoo-lab/internalblue#45]
Hi,

I want to run some profiles based on BIAS and KNOB. I wonder if upper layer protocol can work with Internalblue?

Many thanks.

**Comment by jiska2342** [comment]
Hi @LHKST,

not sure if I understand your question correctly. If you use the BIAS/KNOB PoCs on Linux, the remaining stack is still functional. So, if the Linux stack would not check for the encryption key size after a KNOB attack (which it should, so you might need to remove that check in the Linux stack), you could run protocols like music streaming or tethering afterwards.
