### ISSUE TITLE
Error while performing Knob attack using Nexus 5 wiht Lineage 14.1 os

### ISSUE THREAD

**Issue by abbiy** [seemoo-lab/internalblue#63]
Hi, please its urgent so when i try to perform Knob attack everytime i get the same issue i.e., 

[*] Found multiple adb devices
[*] Connected to 035be4a421519e6f
[!] _sendThreadFunc: No response from the firmware.
[!] sendHciCommand: waiting for response timed out!
[!] initialize_fimware: Failed to send a HCI command to the Bluetooth driver.
            adb: Check if you installed a custom bluetooth.default.so properly on your
              Android device. bluetooth.default.so must contain the string 'hci_inject'.
            hci: You might have insufficient permissions to send this type of command.
[!] connect: Failed to initialize firmware!

I do not know how to resolve it. My setup :- I am Using Nexus5 rooted phone with Lineage14.1 os install. I also copy paste the Bluetooth.default.so file into /system/lib/hw directory. I followed the same steps given in the nexus5 folder.

**Comment by jiska2342** [comment]
There are slightly different Android versions, even within one Android/Lineage major release. In some cases, you might have to build the driver from source to get it working.

You might want to double-check system logs to see where the driver fails, but probably just building from scratch is easier than debugging if you are sure that you followed all steps.
